/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 professor.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/professor.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.beard_geo.geometry} material={materials.Hair} />
        <mesh geometry={nodes.Body_geo.geometry} material={materials.Body} />
        <mesh geometry={nodes.Bowtie_geo.geometry} material={materials.Coat} />
        <mesh geometry={nodes.Coat_geo.geometry} material={materials.Coat} />
        <mesh geometry={nodes.Eye_geo.geometry} material={materials.Eyes} />
        <mesh geometry={nodes.Eyebrow_geo.geometry} material={materials.Hair} />
        <mesh geometry={nodes.Hair_geo.geometry} material={materials.Hair} />
        <mesh geometry={nodes.Pant_geo.geometry} material={materials.PAntandshirt} />
        <mesh geometry={nodes.Shirt_geo.geometry} material={materials.PAntandshirt} />
        <mesh geometry={nodes.Shoes_geo.geometry} material={materials.Shoe} />
        <mesh geometry={nodes.Specs_frame_geo.geometry} material={materials.Specs} />
        <mesh geometry={nodes.Specs_glass_geo.geometry} material={materials.Specs} />
        <mesh geometry={nodes.Teeth_geo.geometry} material={materials.Teeth} />
        <mesh geometry={nodes.Waistcoat_geo.geometry} material={materials.Coat} />
      </group>
    </group>
  )
}

useGLTF.preload('/professor.gltf')
